config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#new'
  resources :contacts, only: [ :create ]
  get '/mentions-legales', to: 'contacts#mentions_legales'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :last_name, validate: true
  attribute :first_name, validate: true
  attribute :email, validate: true, validate: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  attribute :address
  attribute :message, validate: true

  
  def headers
    { 
      #this is the subject for the email generated, it can be anything you want
      subject: "Pâtisserie - Prise de contact",
      to: 'jaye30@gmail.com',
      from: %("#{first_name} #{last_name}" <#{email}>)
      #the from will display the name entered by the user followed by the email
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = :fr
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    @contact.request = request
    if @contact.deliver
      redirect_to root_url, notice: 'Votre message a bien été transmis !'
    else
      @anchor ="anchor-contact"
      render :new
    end
  end

  def mentions_legales
  end

  private

  def contact_params
    params.require(:contact).permit(:last_name, :first_name, :email, :address, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/contacts/_flash.html.erb
<% if !!flash[:notice] %>
  <div class="container-notice">
    <div class="flash-notice">
      <div class='alert alert-error'>
        <button type="button" class="close" data-dismiss="alert" id="flash-close-btn">×</button>
        <div class="flash-content">
          <h2 id="flash-title">MERCI</h2>
          <%= flash[:notice] %>
          <p id="flash-text">Je reviens vers vous dans les plus brefs délais.</p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/_form.erb
<div class="container" id="container-form">
  <h2 id="form-title">ME CONTACTER</h2>
  <%= simple_form_for @contact do |f| %>
    <div class="full-name">
      <%= f.input :last_name, label: "Nom de famille", :required => true, :placeholder => "Dupont" %>
      <%= f.input :first_name, label: "Prénom", :required => true, :placeholder => "Marion" %>
    </div>
    <%= f.input :email, label: "E-mail", :required => true, :placeholder => "marion.dupont@gmail.com" %>
    <%= f.input :address, label: "Adresse", :required => false, :placeholder => "10 rue Abcd 78220 Viroflay" %>
    <%= f.input :message, label: "Message", :as => :text, :required => true, :placeholder => "Votre message" %>
    <div class="submit">
      <%= f.button :submit, 'Envoyer', :class=> "form-button" %>
    </div>
  <% end %>
</div>

app/views/contacts/_form.html.erb
<div class="container" id="container-form">
  <h2 id="form-title">ME CONTACTER</h2>
  <%= simple_form_for @contact do |f| %>
    <div class="full-name">
      <%= f.input :last_name, label: "Nom de famille", :required => true, :placeholder => "Dupont" %>
      <%= f.input :first_name, label: "Prénom", :required => true, :placeholder => "Marion" %>
    </div>
    <%= f.input :email, label: "E-mail", :required => true, :placeholder => "marion.dupont@gmail.com" %>
    <%= f.input :address, label: "Adresse", :required => false, :placeholder => "10 rue Abcd 78220 Viroflay" %>
    <%= f.input :message, label: "Message", :as => :text, :required => true, :placeholder => "Votre message" %>
    <div class="submit">
      <%= f.button :submit, 'Envoyer', :class=> "form-button" %>
    </div>
  <% end %>
  <% if @anchor %>
    <script type="text/javascript">
      window.location.hash = "<%= @anchor %>";
    </script>
  <% end %>
</div>

app/views/contacts/_portfolio.html.erb
<div class="container-portfolio">

  <div class="portfolio-header">
    <a name="anchor-portfolio">
      <h2 class="text-center">FLAVIE SEREN-ROSSO | PATISSIERE PASSIONNEE</h2>
      <%= image_tag("Soulignement_or_endroit.png") %>
    </a>
  </div>
    
  <div class="row">
    <div class="pastry-row" id="row1">
      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611851913/Portfolio%20Flavie/1._Religieuses_jqvxaa.png);">
            </div>
          </div>
          <div class="back bg-gold">
            <div class="header">
              <h4>Religieuses au café</h4>
            </div>
            <div class="content">
              <p>Choux et son craquelin<br>Crème pâtissière café<br>Crème au beurre</p>
            </div>
          </div>
        </div>
      </div>

      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611854329/Portfolio%20Flavie/2._For%C3%AAt_zgvh4m.png);">
            </div>
          </div>
          <div class="back bg-creme">
            <div class="header">
              <h4>Forêt noire aux framboises </h4>
            </div>
            <div class="content">
              <p>Génoise nature<br>Mousse chocolat noir 70%<br>Sirop à la framboise<br>Chantilly à la vanille</p>
            </div>
          </div>
        </div>
      </div>

      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611854329/Portfolio%20Flavie/3._Noix_de_coco_mpywr8.png);">
            </div>
          </div>
          <div class="back bg-gold">
            <div class="header">
              <h4>Nuage coco</h4>
            </div>
            <div class="content">
              <p>Dacquoise coco<br>Croustillant chocolat blanc et coco<br>Mousse coco légère<br>Crémeux chocolat noir </p>
            </div>
          </div>
        </div>
      </div>
        
      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611854329/Portfolio%20Flavie/4._D%C3%B4mes_dx1qmr.png);">
            </div>
          </div>
          <div class="back bg-creme">
            <div class="header">
              <h4>Dômes chocolat praliné</h4>
            </div>
            <div class="content">
              <p>Mousse au chocolat noir 70%<br>Ganache au praliné<br>Croustillant au praliné<br>Crumble à la noisette</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="pastry-row" id="row2">
      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611854329/Portfolio%20Flavie/5._Bavarois_pqdjim.png);">
            </div>
          </div>
          <div class="back bg-creme">
            <div class="header">
              <h4>Bavaroise fruits rouges</h4>
            </div>
            <div class="content">
              <p>Mousse aux fruits rouges<br>Biscuit cuillère<br>Fruits rouges</p>
            </div>
          </div>
        </div>
      </div>

      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611854329/Portfolio%20Flavie/6._Charlotte_cxtqyx.png);">
            </div>
          </div>
          <div class="back bg-gold">
            <div class="header">
              <h4>Charlotte aux poires</h4>
            </div>
            <div class="content">
              <p>Mousse bavaroise à la vanille<br>Biscuit cuillère<br>Poires</p>
            </div>
          </div>
        </div>
      </div>

      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611854329/Portfolio%20Flavie/7._Tartelettes_framboise_shfrwz.png);">
            </div>
          </div>
          <div class="back bg-creme">
            <div class="header">
              <h4>Tartelettes framboises</h4>
            </div>
            <div class="content">
              <p>Pâte sucrée<br>Crème d’amande<br>Ganache montée au chocolat blanc<br>Framboises</p>
            </div>
          </div>
        </div>
      </div>
      
      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611854329/Portfolio%20Flavie/8._Fraisier_jrdsrf.png);">
            </div>
          </div>
          <div class="back bg-gold">
            <div class="header">
              <h4>Fraisier au basilic</h4>
            </div>
            <div class="content">
              <p>Molly cake<br>Pesto basilic amandes<br>Confit de fraises<br>Crème diplomate à la vanille de bourbon</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="pastry-row" id="row3">
      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611854329/Portfolio%20Flavie/9._Galette_tt9kju.png);">
            </div>
          </div>
          <div class="back bg-gold">
            <div class="header">
              <h4>Galette des rois </h4>
            </div>
            <div class="content">
              <p>Pâte feuilletée<br>Crème frangipane à la fleur d’oranger</p>
            </div>
          </div>
        </div>
      </div>

      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611854329/Portfolio%20Flavie/10._Chocolats_zq2e8o.png);">
            </div>
          </div>
          <div class="back bg-creme">
            <div class="header">
              <h4>Chocolats</h4>
            </div>
            <div class="content">
              <p>Enrobage chocolat noir 70% et chocolat dulcey<br>Praliné aux noisettes</p>
            </div>
          </div>
        </div>
      </div>

      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611854330/Portfolio%20Flavie/11._Pains_au_chocolat_cipfmh.png);">
            </div>
          </div>
          <div class="back bg-gold">
            <div class="header">
              <h4>Pains au chocolat</h4>
            </div>
            <div class="content">
              <p>Pâte feuilletée<br>Chocolat noir 70%</p>
            </div>
          </div>
        </div>
      </div>
          
      <div class="card-container">
        <div class="card">
          <div class="front">
            <div class="cover" style="background-image: url(https://res.cloudinary.com/dyrkwhhio/image/upload/v1611854329/Portfolio%20Flavie/12._Macarons_au_chocolat_zk40ea.png);">
            </div>
          </div>
          <div class="back bg-creme">
            <div class="header">
              <h4>Macarons</h4>
            </div>
            <div class="content">
              <p>Ganache au chocolat noir 70%</p>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div id="anchor-position-portray"><a name="anchor-portray"></a></div>
</div>

app/views/contacts/_portray.erb
<div class="container-portray">
  <%= image_tag("Soulignement_or_endroit_épais.png") %>

  <div class="row">
    <%= image_tag("Portrait.png") %>
    <div class="portray-description">
      <h2>FLAVIE SEREN-ROSSO</h2>
      <h3>Une passion depuis sa tendre enfance</h3>
      <p>Flavie est originaire d'Amiens. Passionnée depuis son plus jeune âge par la pâtisserie,
        c'est tout naturellement qu'elle s'est engagée, après des études de commerce à Skema et 
        dans différentes universités internationales, dans un projet entrepreneurial 
        visant à produire et faire découvrir ses biscuits bio au plus grand nombre. </p>

        <p>Quelques années plus tard, et désormais implantée en Île-de-France, 
        Flavie a fait le choix de reprendre ses études en préparant son CAP Pâtisserie ;
        elle continue en parallèle de créer, ou parfois de revisiter, <strong>des pâtisseries</strong>, 
        à son image : <strong>gourmandes et généreuses !</strong></p>

        <p>Découvrez-les et <strong>contactez Flavie</strong> pour tout projet susceptible de l'intéresser.</p>
    </div>
  </div>

  <%= image_tag("Soulignement_or_envers.png") %>
</div>

app/views/contacts/_portray.html.erb
<div class="container-portray">
  <%= image_tag("Soulignement_or_endroit_épais.png") %>

  <div class="row">
    <%= image_tag("Portrait.png") %>
    <div class="portray-description">
      <h2>FLAVIE SEREN-ROSSO</h2>
      <h3>Une passion depuis sa tendre enfance</h3>
      <p>Flavie est originaire d'Amiens. Passionnée depuis son plus jeune âge par la pâtisserie,
        c'est tout naturellement qu'elle s'est engagée, après des études de commerce à Skema et 
        dans différentes universités internationales, dans un projet entrepreneurial 
        visant à produire et faire découvrir ses biscuits bio au plus grand nombre. </p>

        <p>Quelques années plus tard, et désormais implantée en Île-de-France, 
        Flavie a fait le choix de reprendre ses études en préparant son CAP Pâtisserie ;
        elle continue en parallèle de créer, ou parfois de revisiter, <strong>des pâtisseries</strong>, 
        à son image : <strong>gourmandes et généreuses !</strong></p>

        <p>Découvrez-les et <strong>contactez Flavie</strong> pour tout projet susceptible de l'intéresser.</p>
    </div>
  </div>
  <a name="anchor-contact"></a>
  <%= image_tag("Soulignement_or_envers.png") %>
</div>

app/views/contacts/mentions_legales.html.erb
<%= render "shared/header" %>
<div class="container">
  <div class="portfolio-header" id="disclaimer-header">
    <h2>MENTIONS LEGALES</h2>
    <%= image_tag("Soulignement_or_endroit.png") %>
  </div>
  
  <div class="disclaimer-content">
    <div class="disclaimer-paragraph">
      <h5 class="disclaimer-title">Prénom Nom :</h5>
      <p class="disclaimer-text"><strong>Flavie SEREN-ROSSO</strong></p>
    </div>
    <div class="disclaimer-paragraph">
      <h5 class="disclaimer-title">Adresse :</h5>
      <p class="disclaimer-text">78 220 Viroflay</p>
    </div>
    <div class="disclaimer-paragraph">
      <h5 class="disclaimer-title">E-mail :</h5>
      <p class="disclaimer-text">XXXXXXXX</p>
    </div>
    <div class="disclaimer-paragraph" id="last-item">
      <h5 class="disclaimer-title">Mise en ligne du site :</h5>
      <p class="disclaimer-text">XX/XX/2021</p>
    </div>
    <div>
      <h4>Loi informatique et liberté</h4>
      <p>Les informations recueillies font l’objet d’un traitement informatique 
        destiné à répondre aux demandes. Les destinataires des données sont : XXXX@XXXXX.fr<br></p>
      <p>Conformément à la loi « informatique et libertés » du 6 janvier 1978
        modifiée en 2004, vous bénéficiez d’un droit d’accès et de rectification
        aux informations qui vous concernent, que vous pouvez exercer 
        en vous adressant à XXXXX@XXXXX.fr<br></p>
      <p>Vous pouvez également, pour des motifs légitimes, vous opposer 
      au traitement des données vous concernant.</p>
    </div>
    <div>
      <h4>Propriété</h4>
      <p>Le site et les informations qu’il contient sont protégés par la loi
       française sur la propriété intellectuelle et par les conventions 
       internationales. Le site (ou des éléments de son contenu) ne peut être 
       ni reproduit, ni republié, ni retranscrit, ni modifié, ni retransmis 
       sans l’autorisation préalable des ayants droits par écrit 
       (cela ne concerne pas l’utilisation dans le cercle de famille 
       ni l’usage privé).<br></p>
      <p>Tous les textes présents sur le site sont la propriété de Flavie SEREN-ROSSO.<br></p>
      <p>Crédits Photo – © Flavie SEREN-ROSSO</p>
    </div>
  </div>



</div>

app/views/contacts/new.html.erb
<div class="parallax">
  
  <div class="container-banner">

    <a href="<%= root_path %>" id="logo"><h1>FLAVIE<br>SEREN-ROSSO</h1></a>

    <div class="menu">
     <nav class="main-navbar hidden-navbar">
        <div ><a class="navbar-item" href="#anchor-portfolio">Mes Pâtisseries</a></div>
        <div ><a id="navbar-item-2" href="#anchor-portray">Qui suis-je ?</a></div>
        <div ><a class="navbar-item" href="#anchor-contact">Me Contacter</a></div>
      </nav>
      <svg class="ham hamRotate ham1" viewBox="0 0 100 100" width="80" onclick="this.classList.toggle('active')">
        <path class="line top"
              d="m 30,33 h 40 c 0,0 9.044436,-0.654587 9.044436,-8.508902 0,-7.854315 -8.024349,-11.958003 -14.89975,-10.85914 -6.875401,1.098863 -13.637059,4.171617 -13.637059,16.368042 v 40" />
        <path class="line middle" d="m 30,50 h 40" />
        <path class="line bottom"
              d="m 30,67 h 40 c 12.796276,0 15.357889,-11.717785 15.357889,-26.851538 0,-15.133752 -4.786586,-27.274118 -16.667516,-27.274118 -11.88093,0 -18.499247,6.994427 -18.435284,17.125656 l 0.252538,40" />
      </svg>   
    </div>
  </div>

  <%= render "flash" %>

</div>

<div class="overflow">
  <div class="wrapper">
    <div class="sidebar ">
      <ul class="sticky">
        <a href="/" ><i class="fas fa-arrow-circle-up"></i></a>
        <li><a class="sidebar-item" href="/#anchor-portfolio">Mes Pâtisseries</a></li>
        <li><a class="sidebar-item" href="/#anchor-portray">Qui suis-je ?</a></li>
        <li><a class="sidebar-item" href="/#anchor-contact">Me Contacter</a></li>
      </ul>
    </div>
    <div class="main">
      <%= render "portfolio" %>
      <%= render "portray" %>
      <%= render "form" %> 
    </div>
  </div>
</div>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8" />

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

     <!-- Favicon -->
    <%= favicon_link_tag %>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    
  </head>

  <body>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="parallax">
  
  <div class="container-banner">

    <a href="<%= root_path %>" id="logo"><h1>FLAVIE<br>SEREN-ROSSO</h1></a>

    <div class="menu">
     <nav class="main-navbar hidden-navbar">
        <div ><%= link_to "Mes Pâtisseries", '#', class: "navbar-item" %></div>
        <div ><%= link_to "Qui suis-je ?", '#', id: "navbar-item-2" %></div>
        <div ><%= link_to "Me Contacter", '#', class: "navbar-item" %></div>
      </nav>
      <svg class="ham hamRotate ham1" viewBox="0 0 100 100" width="80" onclick="this.classList.toggle('active')">
        <path class="line top"
              d="m 30,33 h 40 c 0,0 9.044436,-0.654587 9.044436,-8.508902 0,-7.854315 -8.024349,-11.958003 -14.89975,-10.85914 -6.875401,1.098863 -13.637059,4.171617 -13.637059,16.368042 v 40" />
        <path class="line middle" d="m 30,50 h 40" />
        <path class="line bottom"
              d="m 30,67 h 40 c 12.796276,0 15.357889,-11.717785 15.357889,-26.851538 0,-15.133752 -4.786586,-27.274118 -16.667516,-27.274118 -11.88093,0 -18.499247,6.994427 -18.435284,17.125656 l 0.252538,40" />
      </svg>   
    </div>

  </div>
</div>

<div class="overflow">

  <%= render "portfolio" %>
  <%= render "portray" %>

  <div class="footer" style="height: 50vh">
  
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <%= image_tag("Soulignement_or_endroit.png") %>
  <div class="footer-container">
      <p class="footer-content">©2021 Conçu et Développé par 
    <%=link_to "Jasmine Seren-Rosso", "https://www.linkedin.com/in/jasminesr/", 
    class: "new-tab", target: "_blank"%></p>
    <p>Tous droits réservés | <%=link_to "Mentions légales", mentions_legales_path, 
    class: "new-tab", target: "_blank"%></p>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="container-banner-shared">

    <a href="<%= root_path %>" id="logo"><h1>FLAVIE<br>SEREN-ROSSO</h1></a>

    <div class="menu">
     <nav class="main-navbar hidden-navbar">
        <div ><a class="navbar-item" href="/#anchor-portfolio">Mes Pâtisseries</a></div>
        <div ><a id="navbar-item-2" href="/#anchor-portray">Qui suis-je ?</a></div>
        <div ><a class="navbar-item" href="/#anchor-contact">Me Contacter</a></div>
      </nav>
      <svg class="ham hamRotate ham1" viewBox="0 0 100 100" width="80" onclick="this.classList.toggle('active')">
        <path class="line top"
              d="m 30,33 h 40 c 0,0 9.044436,-0.654587 9.044436,-8.508902 0,-7.854315 -8.024349,-11.958003 -14.89975,-10.85914 -6.875401,1.098863 -13.637059,4.171617 -13.637059,16.368042 v 40" />
        <path class="line middle" d="m 30,50 h 40" />
        <path class="line bottom"
              d="m 30,67 h 40 c 12.796276,0 15.357889,-11.717785 15.357889,-26.851538 0,-15.133752 -4.786586,-27.274118 -16.667516,-27.274118 -11.88093,0 -18.499247,6.994427 -18.435284,17.125656 l 0.252538,40" />
      </svg>   
    </div>
  </div>